### ISSUE TITLE
愿意支持作者,可是捐献的二维码是什么app的?

### ISSUE THREAD

**Issue by gaoxiang9457** [nulastudio/Freedom#11]
https://github.com/nulastudio/Freedom#buy-me-a-coffee

**Comment by liesauer** [comment]
🙏🙏🙏首先感谢你的支持！
那个是我的`ETH`钱包地址，任何的以太坊钱包APP都可以扫码转账，比如 [imToken](https://www.token.im/)，同时为了方便国内用户捐献赞助，我又加了微信、支付宝两大APP支付码。
