### ISSUE TITLE
大佬，为什么我今天点击扫码链接里面什么东西都没了呢？是点错地方了吗

### ISSUE THREAD

**Issue by muikmuikdance** [nulastudio/Freedom#14]

**Comment by liesauer** [comment]
最近的源失效比较多，我也在找一些公开的源进行采集聚合，昨天调了下程序，把不能用的源全下了，目前仅剩下`VisionNetwork`的源还能用。我看了下，扫码页面还是有东西的，你可能刚好碰上我在改程序吧，或者碰巧没采集成功（现在的逻辑是先清空再采集的，防止因为没采集成功而长时间残留了大量的旧的不可用源）。另外你没有在用订阅吗？订阅的话放进程序里会自动更新的。

**Comment by liesauer** [comment]
我刚刚也发现了确实会有采集不到的情况，初步分析是采集`VisionNetwork `源时超时导致采集失败，因为`VisionNetwork `源是托管在`GitHub`上的，所以访问起来是有一定的几率会超时，我先把超时时间往上调一调，看看效果先。

**Comment by liesauer** [comment]
新添了一个`Lncn.org`的源
