### ISSUE TITLE
大佬在不在？

### ISSUE THREAD

**Issue by mijaclan556** [nulastudio/Freedom#15]
为什么用不了啊！！！已支持0.01

**Comment by liesauer** [comment]
是指节点连不上还是订阅用不了？

**Comment by mijaclan556** [comment]
连上，就是用不了。------------------ 原始邮件 ------------------
发件人: "L!εsAμεr"<notifications@github.com>
发送时间: 2019年12月9日(星期一) 下午2:15
收件人: "nulastudio/Freedom"<Freedom@noreply.github.com>;
抄送: "mijaclan556"<2734473891@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [nulastudio/Freedom] 大佬在不在？ (#15)



是指节点连不上还是订阅用不了？
 
&mdash;

**Comment by mijaclan556** [comment]
节点连上------------------ 原始邮件 ------------------
发件人: "L!εsAμεr"<notifications@github.com>
发送时间: 2019年12月9日(星期一) 下午2:15
收件人: "nulastudio/Freedom"<Freedom@noreply.github.com>;
抄送: "mijaclan556"<2734473891@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [nulastudio/Freedom] 大佬在不在？ (#15)



是指节点连不上还是订阅用不了？
 
&mdash;

**Comment by liesauer** [comment]
现在的节点普遍失效较快，也没什么好办法，打算在年前对这个项目升级并将用户引导到微信端，对用户群体做一个管理，也能缓解一下这种情况，现在的订阅是完全公开的，传播得快失效也快。

**Comment by mijaclan556** [comment]
那为什么，手机的可以用呢？如thunder vpn。。求解------------------ 原始邮件 ------------------
发件人: "L!εsAμεr"<notifications@github.com>
发送时间: 2019年12月9日(星期一) 下午3:28
收件人: "nulastudio/Freedom"<Freedom@noreply.github.com>;
抄送: "mijaclan556"<2734473891@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [nulastudio/Freedom] 大佬在不在？ (#15)



现在的节点普遍失效较快，也没什么好办法，打算在年前对这个项目升级并将用户引导到微信端，对用户群体做一个管理，也能缓解一下这种情况，现在的订阅是完全公开的，传播得快失效也快。
 
&mdash;

**Comment by liesauer** [comment]
你是说用thunder vpn这个软件连我们的节点，还是连他们自己的节点

**Comment by mijaclan556** [comment]
这个软件自带节点的，在国内用手机下载好就可以用了。------------------ 原始邮件 ------------------
发件人: "L!εsAμεr"<notifications@github.com>
发送时间: 2019年12月9日(星期一) 下午3:45
收件人: "nulastudio/Freedom"<Freedom@noreply.github.com>;
抄送: "mijaclan556"<2734473891@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [nulastudio/Freedom] 大佬在不在？ (#15)



你是说用thunder vpn这个软&#x4EF6;连我们的节点，还是连他们自己的节点
 
&mdash;

**Comment by liesauer** [comment]
这类软件在国内是没有上架的，所以活得也长，不像我这个项目，我这个项目的节点都是采集回来的，在别的地方也有的，所以活得就没这么长



 
发件人： mijaclan556
发送时间： 2019-12-09 19:41
收件人： nulastudio/Freedom
抄送： L!εsAμεr; Comment
主题： Re: [nulastudio/Freedom] 大佬在不在？ (#15)
这个软件自带节点的，在国内用手机下载好就可以用了。------------------ 原始邮件 ------------------ 
发件人: "L!εsAμεr"<notifications@github.com> 
发送时间: 2019年12月9日(星期一) 下午3:45 
收件人: "nulastudio/Freedom"<Freedom@noreply.github.com>; 
抄送: "mijaclan556"<2734473891@qq.com>;"Author"<author@noreply.github.com>; 
主题: Re: [nulastudio/Freedom] 大佬在不在？ (#15) 



你是说用thunder vpn这个软&#x4EF6;连我们的节点，还是连他们自己的节点 

&mdash;

**Comment by mijaclan556** [comment]
原来如此。 感谢分享。------------------ 原始邮件 ------------------
发件人: "L!εsAμεr"<notifications@github.com>
发送时间: 2019年12月9日(星期一) 晚上7:45
收件人: "nulastudio/Freedom"<Freedom@noreply.github.com>;
抄送: "mijaclan556"<2734473891@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [nulastudio/Freedom] 大佬在不在？ (#15)


这类软&#x4EF6;在国内是没有上架的，所以活得也长，不像我这个项目，我这个项目的节点都是采集回来的，在别的地方也有的，所以活得就没这么长 
 
 
 
   
 发&#x4EF6;人： mijaclan556 
 发送时间： 2019-12-09 19:41 
 收&#x4EF6;人： nulastudio/Freedom 
 抄送： L!εsAμεr; Comment 
 主题： Re: [nulastudio/Freedom] 大佬在不在？ (#15) 
 这个软&#x4EF6;自带节点的，在国内用手机下载好就可以用了。------------------ 原始邮&#x4EF6; ------------------  
 发&#x4EF6;人: "L!εsAμεr"<notifications@github.com>  
 发送时间: 2019年12月9日(星期一) 下午3:45  
 收&#x4EF6;人: "nulastudio/Freedom"<Freedom@noreply.github.com>;  
 抄送: "mijaclan556"<2734473891@qq.com>;"Author"<author@noreply.github.com>;  
 主题: Re: [nulastudio/Freedom] 大佬在不在？ (#15)  
 
 
 
 你是说用thunder vpn这个软&#x4EF6;连我们的节点，还是连他们自己的节点  
 
 &mdash;  
 You are receiving this because you authored the thread.  
 Reply to this email directly, view it on GitHub, or unsubscribe.  
 — 
 You are receiving this because you commented. 
 Reply to this email directly, view it on GitHub, or unsubscribe. 
 
&mdash;
