### ISSUE TITLE
全部不能用，怎么回事

### ISSUE THREAD

**Issue by anlexN** [nulastudio/Freedom#3]

**Comment by liesauer** [comment]
近期敏感时期，日本那些有的还是可以用的。

![Screenshot_20190605-141116__01](https://user-images.githubusercontent.com/8676741/58934105-16485d80-879c-11e9-8002-5351060240a4.jpg)

**Comment by anlexN** [comment]
下载是不是限速了？

**Comment by liesauer** [comment]
> 下载是不是限速了？

应该是吧，目前所有公开组的账号都是采集来的，如果你有大量的下载需求的话还是建议自买备一个。
