### ISSUE TITLE
请问订阅地址是崩了吗 显示504超时了

### ISSUE THREAD

**Issue by lhllhx** [nulastudio/Freedom#8]
如题

**Comment by liesauer** [comment]
最近抓取服务器有点问题，预计今晚能恢复，不好意思！

**Comment by liesauer** [comment]
已经修复，且加入缓存机制，当抓取服务器故障时可自动切换到缓存的订阅，保证订阅服务的可用性！但缓存的订阅的ping值检测以及服务器在线检测都是不准确的，过时的。
